version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=localhost
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_DATABASE=nexatest
      - DB_PORT=3306
    ports:
      - "3000:3000"
